In [ ]:
import tabm
import pandas as pd

pd.set_option('display.max_columns', 1000)
pd.set_option('display.width', 1000)

In [ ]:
df_cust = pd.read_pickle('./../data/processed/customer_nodes_training.p')
df_event = pd.read_pickle('./../data/processed/event_table_training.p')
df_prod = pd.read_pickle('./../data/processed/product_nodes_training.p')
df_cust.head()

   hash(customerId)  yearOfBirth  isMale shippingCountry  premier  salesPerCustomer  returnsPerCustomer  customerReturnRate  customerId_level_return_code_A  customerId_level_return_code_B  customerId_level_return_code_C  customerId_level_return_code_D  customerId_level_return_code_E  customerId_level_return_code_D  customerId_level_return_code_F  customerId_level_return_code_G  customerId_level_return_code_H  customerId_level_return_code_I  customerId_level_return_code_J  customerId_level_return_code_K  customerId_level_return_code_L  Country_A  Country_B  Country_C  Country_D  Country_E  Country_F  Country_G  Country_H  Country_I
1        1901128802         1992       0       Country_G        0                 4                   1            0.250000                             0.0                             0.0                             0.0                             0.0                             0.0                        0.000000                             0.0                        0.000000                             0.0                             1.0                             0.0                             0.0                             0.0          0          0          0          0          0          0          1          0          0
2       -1347052608         2004       0       Country_E        0                 7                   3            0.428571                             0.0                             0.0                             0.0                             0.0                             0.0                        0.000000                             0.0                        0.000000                             0.0                             1.0                             0.0                             0.0                             0.0          0          0          0          0          1          0          0          0          0
3        1968224587         1975       1       Country_C        0                 9                   1            0.111111                             0.0                             0.0                             0.0                             0.0                             0.0                        1.000000                             0.0                        0.000000                             0.0                             0.0                             0.0                             0.0                             0.0          0          0          1          0          0          0          0          0          0
4         101496816         1995       0       Country_G        0                28                  22            0.785714                             0.0                             0.0                             0.0                             0.0                             0.0                        0.954545                             0.0                        0.045455                             0.0                             0.0                             0.0                             0.0                             0.0          0          0          0          0          0          0          1          0          0
5       -1490187487         2002       0       Country_E        0                12                  10            0.833333                             0.0                             0.0                             0.0                             0.0                             0.0                        1.000000                             0.0                        0.000000                             0.0                             0.0                             0.0                             0.0                             0.0          0          0          0          0          1          0          0          0          0

In [ ]:
df_event['isReturned'].describe()

count    1.369133e+06
mean     5.530704e-01
std      4.971757e-01
min      0.000000e+00
25%      0.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      1.000000e+00
Name: isReturned, dtype: float64

In [ ]:
df_event.head()

       hash(variantID)  hash(customerId)  isReturned
1  8262848653457749222       -1460347154           0
2 -1567841582771857859       -1457538806           1
3  7754674097260878582       -1223268503           1
4 -4404944052740977793         824610854           1
5  1654187440431947983       -1831163455           1

In [ ]:
df_prod.iloc[0]

hash(variantID)                  4550259741504178673
hash(productID)                  5879799799090574153
productType                            productType_B
hash(supplierRef)                          221571216
brandDesc                                    Brand_K
avgGbpPrice                                    27.61
avgDiscountValue                               18.17
salesPerProduct                                   18
returnsPerProduct                                  7
productReturnRate                           0.388889
variantID_level_return_code_A                    0.0
variantID_level_return_code_B                    0.0
variantID_level_return_code_C                    0.0
variantID_level_return_code_D                    0.0
variantID_level_return_code_E                    0.0
variantID_level_return_code_D                    1.0
variantID_level_return_code_F                    0.0
variantID_level_return_code_G                    0.0
variantID_level_return_code_H                    0.0
variantID_level_return_code_I                    0.0
variantID_level_return_code_J                    0.0
variantID_level_return_code_K                    0.0
variantID_level_return_code_L                    0.0
Brand_A                                            0
Brand_B                                            0
Brand_C                                            0
Brand_D                                            0
Brand_E                                            0
Brand_F                                            0
Brand_G                                            0
Brand_I                                            0
Brand_J                                            0
Brand_K                                            1
productType_A                                      0
productType_B                                      1
productType_C                                      0
productType_D                                      0
productType_E                                      0
productType_F                                      0
productType_G                                      0
productType_H                                      0
productType_I                                      0
productType_J                                      0
productType_K                                      0
Name: 1, dtype: object

In [ ]:
df = df_event.merge(df_prod, how='inner', on='hash(variantID)').merge(df_cust, how='inner', on='hash(customerId)')
df.head()

,hash(variantID),hash(customerId),isReturned,hash(productID),productType,hash(supplierRef),brandDesc,avgGbpPrice,avgDiscountValue,salesPerProduct,returnsPerProduct,productReturnRate,variantID_level_return_code_A,variantID_level_return_code_B,variantID_level_return_code_C,variantID_level_return_code_D,variantID_level_return_code_E,variantID_level_return_code_D,variantID_level_return_code_F,variantID_level_return_code_G,variantID_level_return_code_H,variantID_level_return_code_I,variantID_level_return_code_J,variantID_level_return_code_K,variantID_level_return_code_L,Brand_A,Brand_B,Brand_C,Brand_D,Brand_E,Brand_F,Brand_G,Brand_I,Brand_J,Brand_K,productType_A,productType_B,productType_C,productType_D,productType_E,productType_F,productType_G,productType_H,productType_I,productType_J,productType_K,yearOfBirth,isMale,shippingCountry,premier,salesPerCustomer,returnsPerCustomer,customerReturnRate,customerId_level_return_code_A,customerId_level_return_code_B,customerId_level_return_code_C,customerId_level_return_code_D,customerId_level_return_code_E,customerId_level_return_code_D,customerId_level_return_code_F,customerId_level_return_code_G,customerId_level_return_code_H,customerId_level_return_code_I,customerId_level_return_code_J,customerId_level_return_code_K,customerId_level_return_code_L,Country_A,Country_B,Country_C,Country_D,Country_E,Country_F,Country_G,Country_H,Country_I
0,1773657695342074536,2143516120,1,-4201272420282576798,productType_B,-962650151,Brand_B,14.75,17.14,14,6,0.428571,0.0,0.0,0.0,0.166667,0.0,0.333333,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1981,0,Country_G,0,6,4,0.666667,0.0,0.00,0.0,0.000000,0.0,0.250000,0.0,0.0,0.0,0.250000,0.50,0.000000,0.0,0,0,0,0,0,0,1,0,0
1,1773657695342074536,-1662228049,1,-4201272420282576798,productType_B,-962650151,Brand_B,14.75,17.14,14,6,0.428571,0.0,0.0,0.0,0.166667,0.0,0.333333,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1984,0,Country_G,0,16,12,0.750000,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.666667,0.25,0.083333,0.0,0,0,0,0,0,0,1,0,0
2,-5435047160525608540,-828983942,0,-4201272420282576798,productType_B,-962650151,Brand_B,14.75,17.14,4,2,0.500000,0.0,0.5,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1998,0,Country_G,0,10,3,0.300000,0.0,0.00,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.000000,0.00,0.333333,0.0,0,0,0,0,0,0,1,0,0
3,1537024608144344266,993695551,0,2691279678240636493,productType_B,-1872854279,Brand_B,24.00,18.00,5,1,0.200000,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1987,0,Country_E,0,5,4,0.800000,0.0,0.00,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.000000,0.50,0.000000,0.0,0,0,0,0,1,0,0,0,0
4,3067996428822420629,278586302,1,2691279678240636493,productType_B,-1872854279,Brand_B,24.00,18.00,4,2,0.500000,0.0,0.0,0.0,0.500000,0.0,0.000000,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1981,0,Country_H,0,4,4,1.000000,0.0,0.25,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.25,0.500000,0.0,0,0,0,0,0,0,0,1,0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848454 entries, 0 to 848453
Data columns (total 75 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hash(variantID)                 848454 non-null  int64
 1   hash(customerId)                848454 non-null  int64
 2   isReturned                      848454 non-null  int64
 3   hash(productID)                 848454 non-null  int64
 4   productType                     848454 non-null  object
 5   hash(supplierRef)               848454 non-null  int64
 6   brandDesc                       848454 non-null  object
 7   avgGbpPrice                     848454 non-null  float64
 8   avgDiscountValue                848454 non-null  float64
 9   salesPerProduct                 848454 non-null  int64
 10  returnsPerProduct               848454 non-null  int64
 11  productReturnRate               848454 non-null  float64
 12  variantID_level_return_code_A   848454 non-null  float64
 13  variantID_level_return_code_B   848454 non-null  float64
 14  variantID_level_return_code_C   848454 non-null  float64
 15  variantID_level_return_code_D   848454 non-null  float64
 16  variantID_level_return_code_E   848454 non-null  float64
 17  variantID_level_return_code_D   848454 non-null  float64
 18  variantID_level_return_code_F   848454 non-null  float64
 19  variantID_level_return_code_G   848454 non-null  float64
 20  variantID_level_return_code_H   848454 non-null  float64
 21  variantID_level_return_code_I   848454 non-null  float64
 22  variantID_level_return_code_J   848454 non-null  float64
 23  variantID_level_return_code_K   848454 non-null  float64
 24  variantID_level_return_code_L   848454 non-null  float64
 25  Brand_A                         848454 non-null  int64
 26  Brand_B                         848454 non-null  int64
 27  Brand_C                         848454 non-null  int64
 28  Brand_D                         848454 non-null  int64
 29  Brand_E                         848454 non-null  int64
 30  Brand_F                         848454 non-null  int64
 31  Brand_G                         848454 non-null  int64
 32  Brand_I                         848454 non-null  int64
 33  Brand_J                         848454 non-null  int64
 34  Brand_K                         848454 non-null  int64
 35  productType_A                   848454 non-null  int64
 36  productType_B                   848454 non-null  int64
 37  productType_C                   848454 non-null  int64
 38  productType_D                   848454 non-null  int64
 39  productType_E                   848454 non-null  int64
 40  productType_F                   848454 non-null  int64
 41  productType_G                   848454 non-null  int64
 42  productType_H                   848454 non-null  int64
 43  productType_I                   848454 non-null  int64
 44  productType_J                   848454 non-null  int64
 45  productType_K                   848454 non-null  int64
 46  yearOfBirth                     848454 non-null  int64
 47  isMale                          848454 non-null  int64
 48  shippingCountry                 848454 non-null  object
 49  premier                         848454 non-null  int64
 50  salesPerCustomer                848454 non-null  int64
 51  returnsPerCustomer              848454 non-null  int64
 52  customerReturnRate              848454 non-null  float64
 53  customerId_level_return_code_A  848454 non-null  float64
 54  customerId_level_return_code_B  848454 non-null  float64
 55  customerId_level_return_code_C  848454 non-null  float64
 56  customerId_level_return_code_D  848454 non-null  float64
 57  customerId_level_return_code_E  848454 non-null  float64
 58  customerId_level_return_code_D  848454 non-null  float64
 59  customerId_level_return_code_F  848454 non-null  float64
 60  customerId_level_return_code_G  848454 non-null  float64
 61  customerId_level_return_code_H  848454 non-null  float64
 62  customerId_level_return_code_I  848454 non-null  float64
 63  customerId_level_return_code_J  848454 non-null  float64
 64  customerId_level_return_code_K  848454 non-null  float64
 65  customerId_level_return_code_L  848454 non-null  float64
 66  Country_A                       848454 non-null  int64
 67  Country_B                       848454 non-null  int64
 68  Country_C                       848454 non-null  int64
 69  Country_D                       848454 non-null  int64
 70  Country_E                       848454 non-null  int64
 71  Country_F                       848454 non-null  int64
 72  Country_G                       848454 non-null  int64
 73  Country_H                       848454 non-null  int64
 74  Country_I                       848454 non-null  int64
dtypes: float64(30), int64(42), object(3)
memory usage: 485.5+ MB

In [ ]:
df_t = df.copy()
df_t = df_t.drop(['hash(variantID)', 'hash(productID)', 'hash(customerId)', 'productType', 'hash(supplierRef)', 'brandDesc', 'shippingCountry'], axis = 1)

In [ ]:
df_t.head()

,isReturned,avgGbpPrice,avgDiscountValue,salesPerProduct,returnsPerProduct,productReturnRate,variantID_level_return_code_A,variantID_level_return_code_B,variantID_level_return_code_C,variantID_level_return_code_D,variantID_level_return_code_E,variantID_level_return_code_D,variantID_level_return_code_F,variantID_level_return_code_G,variantID_level_return_code_H,variantID_level_return_code_I,variantID_level_return_code_J,variantID_level_return_code_K,variantID_level_return_code_L,Brand_A,Brand_B,Brand_C,Brand_D,Brand_E,Brand_F,Brand_G,Brand_I,Brand_J,Brand_K,productType_A,productType_B,productType_C,productType_D,productType_E,productType_F,productType_G,productType_H,productType_I,productType_J,productType_K,yearOfBirth,isMale,premier,salesPerCustomer,returnsPerCustomer,customerReturnRate,customerId_level_return_code_A,customerId_level_return_code_B,customerId_level_return_code_C,customerId_level_return_code_D,customerId_level_return_code_E,customerId_level_return_code_D,customerId_level_return_code_F,customerId_level_return_code_G,customerId_level_return_code_H,customerId_level_return_code_I,customerId_level_return_code_J,customerId_level_return_code_K,customerId_level_return_code_L,Country_A,Country_B,Country_C,Country_D,Country_E,Country_F,Country_G,Country_H,Country_I
0,1,14.75,17.14,14,6,0.428571,0.0,0.0,0.0,0.166667,0.0,0.333333,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1981,0,0,6,4,0.666667,0.0,0.00,0.0,0.000000,0.0,0.250000,0.0,0.0,0.0,0.250000,0.50,0.000000,0.0,0,0,0,0,0,0,1,0,0
1,1,14.75,17.14,14,6,0.428571,0.0,0.0,0.0,0.166667,0.0,0.333333,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1984,0,0,16,12,0.750000,0.0,0.00,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.666667,0.25,0.083333,0.0,0,0,0,0,0,0,1,0,0
2,0,14.75,17.14,4,2,0.500000,0.0,0.5,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.5,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1998,0,0,10,3,0.300000,0.0,0.00,0.0,0.333333,0.0,0.333333,0.0,0.0,0.0,0.000000,0.00,0.333333,0.0,0,0,0,0,0,0,1,0,0
3,0,24.00,18.00,5,1,0.200000,0.0,0.0,0.0,0.000000,0.0,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1987,0,0,5,4,0.800000,0.0,0.00,0.0,0.000000,0.0,0.500000,0.0,0.0,0.0,0.000000,0.50,0.000000,0.0,0,0,0,0,1,0,0,0,0
4,1,24.00,18.00,4,2,0.500000,0.0,0.0,0.0,0.500000,0.0,0.000000,0.0,0.0,0.0,0.5,0.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1981,0,0,4,4,1.000000,0.0,0.25,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.000000,0.25,0.500000,0.0,0,0,0,0,0,0,0,1,0

In [ ]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 848454 entries, 0 to 848453
Data columns (total 68 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   isReturned                      848454 non-null  int64
 1   avgGbpPrice                     848454 non-null  float64
 2   avgDiscountValue                848454 non-null  float64
 3   salesPerProduct                 848454 non-null  int64
 4   returnsPerProduct               848454 non-null  int64
 5   productReturnRate               848454 non-null  float64
 6   variantID_level_return_code_A   848454 non-null  float64
 7   variantID_level_return_code_B   848454 non-null  float64
 8   variantID_level_return_code_C   848454 non-null  float64
 9   variantID_level_return_code_D   848454 non-null  float64
 10  variantID_level_return_code_E   848454 non-null  float64
 11  variantID_level_return_code_D   848454 non-null  float64
 12  variantID_level_return_code_F   848454 non-null  float64
 13  variantID_level_return_code_G   848454 non-null  float64
 14  variantID_level_return_code_H   848454 non-null  float64
 15  variantID_level_return_code_I   848454 non-null  float64
 16  variantID_level_return_code_J   848454 non-null  float64
 17  variantID_level_return_code_K   848454 non-null  float64
 18  variantID_level_return_code_L   848454 non-null  float64
 19  Brand_A                         848454 non-null  int64
 20  Brand_B                         848454 non-null  int64
 21  Brand_C                         848454 non-null  int64
 22  Brand_D                         848454 non-null  int64
 23  Brand_E                         848454 non-null  int64
 24  Brand_F                         848454 non-null  int64
 25  Brand_G                         848454 non-null  int64
 26  Brand_I                         848454 non-null  int64
 27  Brand_J                         848454 non-null  int64
 28  Brand_K                         848454 non-null  int64
 29  productType_A                   848454 non-null  int64
 30  productType_B                   848454 non-null  int64
 31  productType_C                   848454 non-null  int64
 32  productType_D                   848454 non-null  int64
 33  productType_E                   848454 non-null  int64
 34  productType_F                   848454 non-null  int64
 35  productType_G                   848454 non-null  int64
 36  productType_H                   848454 non-null  int64
 37  productType_I                   848454 non-null  int64
 38  productType_J                   848454 non-null  int64
 39  productType_K                   848454 non-null  int64
 40  yearOfBirth                     848454 non-null  int64
 41  isMale                          848454 non-null  int64
 42  premier                         848454 non-null  int64
 43  salesPerCustomer                848454 non-null  int64
 44  returnsPerCustomer              848454 non-null  int64
 45  customerReturnRate              848454 non-null  float64
 46  customerId_level_return_code_A  848454 non-null  float64
 47  customerId_level_return_code_B  848454 non-null  float64
 48  customerId_level_return_code_C  848454 non-null  float64
 49  customerId_level_return_code_D  848454 non-null  float64
 50  customerId_level_return_code_E  848454 non-null  float64
 51  customerId_level_return_code_D  848454 non-null  float64
 52  customerId_level_return_code_F  848454 non-null  float64
 53  customerId_level_return_code_G  848454 non-null  float64
 54  customerId_level_return_code_H  848454 non-null  float64
 55  customerId_level_return_code_I  848454 non-null  float64
 56  customerId_level_return_code_J  848454 non-null  float64
 57  customerId_level_return_code_K  848454 non-null  float64
 58  customerId_level_return_code_L  848454 non-null  float64
 59  Country_A                       848454 non-null  int64
 60  Country_B                       848454 non-null  int64
 61  Country_C                       848454 non-null  int64
 62  Country_D                       848454 non-null  int64
 63  Country_E                       848454 non-null  int64
 64  Country_F                       848454 non-null  int64
 65  Country_G                       848454 non-null  int64
 66  Country_H                       848454 non-null  int64
 67  Country_I                       848454 non-null  int64
dtypes: float64(30), int64(38)
memory usage: 440.2 MB

In [ ]:
cols = pd.Series(df_t.columns)
for name in cols[cols.duplicated()].unique():
    idx = cols[cols == name].index
    cols.iloc[idx] = [f'{name}_{i}' if i > 0 else name for i in range(len(idx))]
df_t.columns = cols

In [ ]:
from typing import Optional
import numpy as np
import sklearn
import torch
import torch.nn as nn
import torch.optim
from torch import Tensor
import math
from copy import deepcopy
from sklearn.preprocessing import StandardScaler
import sklearn.model_selection

In [ ]:
num_cols_to_scale = ['avgGbpPrice', 'avgDiscountValue', 'salesPerProduct',
                     'returnsPerProduct', 'salesPerCustomer', 'returnsPerCustomer',
                     'salesPerCustomer', 'returnsPerCustomer']

features = df_t.columns.drop('isReturned')
X_num = df_t[features].to_numpy(np.float32)
Y = df_t['isReturned'].to_numpy(np.int64)

scale_idx = [df_t.columns.get_loc(col) for col in num_cols_to_scale]

idx = np.arange(len(Y))
trainval_idx, test_idx = sklearn.model_selection.train_test_split(idx, train_size=0.8, random_state=42)
train_idx, val_idx = sklearn.model_selection.train_test_split(trainval_idx, train_size=0.8, random_state=42)

scaler = StandardScaler()
scaler.fit(X_num[train_idx][:, scale_idx])

def scale_features(X):
    X_scaled = X.copy()
    X_scaled[:, scale_idx] = scaler.transform(X[:, scale_idx])
    return X_scaled

data_numpy = {
    'train': {'x_num': scale_features(X_num[train_idx]), 'y': Y[train_idx]},
    'val':   {'x_num': scale_features(X_num[val_idx]),   'y': Y[val_idx]},
    'test':  {'x_num': scale_features(X_num[test_idx]),  'y': Y[test_idx]},
}

for part, part_data in data_numpy.items():
    for key, value in part_data.items():
        print(f'{part:<5}    {key:<5}    {value.shape!r:<10}    {value.dtype}')

train    x_num    (543010, 67)    float32
train    y        (543010,)     int64
val      x_num    (135753, 67)    float32
val      y        (135753,)     int64
test     x_num    (169691, 67)    float32
test     y        (169691,)     int64

In [ ]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

data = {
    part: {k: torch.as_tensor(v, device=device) for k, v in data_numpy[part].items()}
    for part in data_numpy
}

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

In [ ]:
Y_train = data_numpy['train']['y'].copy()
Y_train = torch.as_tensor(Y_train, device=device)

In [ ]:
amp_dtype = (
    torch.bfloat16
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    else torch.float16
    if torch.cuda.is_available()
    else None
)

amp_enabled = False and amp_dtype is not None
grad_scaler = torch.cuda.amp.GradScaler() if amp_dtype is torch.float16 else None  # type: ignore

compile_model = False

print(f'Device:        {device.type.upper()}')
print(f'AMP:           {amp_enabled}{f" ({amp_dtype})"if amp_enabled else ""}')
print(f'torch.compile: {compile_model}')

Device:        CUDA
AMP:           False
torch.compile: False

In [ ]:
n_num_features = data_numpy['train']['x_num'].shape[1]
cat_cardinalities = None  
n_classes = 2            
num_embeddings = None

In [ ]:
num_embeddings = None

model = tabm.TabM.make(
    n_num_features=n_num_features,
    cat_cardinalities=cat_cardinalities,
    d_out=1 if n_classes is None else n_classes,
    num_embeddings=num_embeddings,
).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-3, weight_decay=3e-4)
gradient_clipping_norm: Optional[float] = 1.0

if compile_model:
    # NOTE
    # `torch.compile(model, mode="reduce-overhead")` caused issues during training,
    # so the `mode` argument is not used.
    model = torch.compile(model)
    evaluation_mode = torch.no_grad
else:
    evaluation_mode = torch.inference_mode

In [ ]:
# A quick reminder: TabM represents an ensemble of k MLPs.
#
# The option below determines if the MLPs are trained
# on the same batches (share_training_batches=True) or
# on different batches. Technically, this option determines:
# - How the loss function is implemented.
# - How the training batches are constructed.
#
# `True` is recommended by default because of better training efficiency.
# On some tasks, `False` may provide better performance.
share_training_batches = False

In [ ]:
@torch.autocast(device.type, enabled=amp_enabled, dtype=amp_dtype)  # type: ignore[code]
def apply_model(part: str, idx: Tensor) -> Tensor:
    return (
        model(
            data[part]['x_num'][idx],
            data[part]['x_cat'][idx] if 'x_cat' in data[part] else None,
        )
        .float()
    )


base_loss_fn = (nn.functional.cross_entropy)

In [ ]:
def loss_fn(y_pred: Tensor, y_true: Tensor) -> Tensor:
    # TabM produces k predictions. Each of them must be trained separately.

    # Regression:     (batch_size, k)            -> (batch_size * k,)
    # Classification: (batch_size, k, n_classes) -> (batch_size * k, n_classes)
    y_pred = y_pred.flatten(0, 1)

    if share_training_batches:
        # (batch_size,) -> (batch_size * k,)
        y_true = y_true.repeat_interleave(model.backbone.k)
    else:
        # (batch_size, k) -> (batch_size * k,)
        y_true = y_true.flatten(0, 1)

    return base_loss_fn(y_pred, y_true)

In [ ]:
@evaluation_mode()
def evaluate(part: str) -> dict:
    model.eval()

    eval_batch_size = 8096

    logits = torch.cat(
        [
            apply_model(part, idx)
            for idx in torch.arange(len(data[part]['y']), device=device).split(
                eval_batch_size
            )
        ]
    )  # (N, k, C)

    y_true = data[part]['y']  # (N,)

    # ===== probabilities =====
    probs = torch.softmax(logits, dim=-1).mean(1)  # (N, C)

    loss = nn.functional.cross_entropy(
        probs.log(),
        y_true,
    ).item()

    y_true_np = y_true.cpu().numpy()
    probs_np = probs.cpu().numpy()
    y_pred = probs_np.argmax(axis=1)

    roc_auc = sklearn.metrics.roc_auc_score(y_true_np, probs_np[:, 1])
    acc = accuracy_score(y_true_np, y_pred)
    precision = precision_score(y_true_np, y_pred, zero_division=0)
    recall = recall_score(y_true_np, y_pred, zero_division=0)
    f1 = f1_score(y_true_np, y_pred, zero_division=0)

    return {
        "roc_auc": float(roc_auc),
        "loss": float(loss),
        "accuracy": float(acc),
        "precision": float(precision),
        "recall": float(recall),
        "f1": float(f1),
    }



m = evaluate("test")
print(
    f'Test before training | '
    f'roc_auc={m["roc_auc"]:.4f} '
    f'loss={m["loss"]:.4f} '
    f'f1={m["f1"]:.4f}'
)

Test before training | roc_auc=0.5570 loss=0.7107 f1=0.0174

In [ ]:
import torch
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

n_epochs = 40
train_size = len(train_idx)
batch_size = 1024
epoch_size = math.ceil(train_size / batch_size)

epoch = -1
metrics = {
    "val": {"roc_auc": -math.inf},
    "test": {"roc_auc": -math.inf},
}



def make_checkpoint() -> dict:
    return deepcopy(
        {
            'model': model.state_dict(),
            'optimizer': optimizer.state_dict(),
            'epoch': epoch,
            'metrics': metrics,
        }
    )


best_checkpoint = make_checkpoint()

patience = 16
remaining_patience = patience

for epoch in range(n_epochs):
    batches = (
        torch.randperm(train_size, device=device).split(batch_size)
        if share_training_batches
        else (
            torch.rand((train_size, model.backbone.k), device=device)
            .argsort(dim=0)
            .split(batch_size, dim=0)
        )
    )

    for batch_idx in batches:
        model.train()
        optimizer.zero_grad()

        loss = loss_fn(
            apply_model('train', batch_idx),
            Y_train[batch_idx],
        )

        if grad_scaler is None:
            loss.backward()
        else:
            grad_scaler.scale(loss).backward()

        if gradient_clipping_norm is not None:
            if grad_scaler is not None:
                grad_scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(
                model.parameters(), gradient_clipping_norm
            )

        if grad_scaler is None:
            optimizer.step()
        else:
            grad_scaler.step(optimizer)
            grad_scaler.update()

    metrics = {part: evaluate(part) for part in ['val', 'test']}
    val_score_improved = (
        metrics['val']['roc_auc']
        > best_checkpoint['metrics']['val']['roc_auc']
    )

    print(
        f'{"*" if val_score_improved else " "}'
        f' [epoch] {epoch:<3}'
        f' | val: '
        f'loss={metrics["val"]["loss"]:.4f} '
        f'roc_auc={metrics["val"]["roc_auc"]:.4f} '
        f'f1={metrics["val"]["f1"]:.4f}'
        f' | test: '
        f'loss={metrics["test"]["loss"]:.4f} '
        f'roc_auc={metrics["test"]["roc_auc"]:.4f} '
        f'f1={metrics["test"]["f1"]:.4f}'
    )
    if val_score_improved:
        best_checkpoint = make_checkpoint()
        remaining_patience = patience
    else:
        remaining_patience -= 1

    if remaining_patience < 0:
        break

model.load_state_dict(best_checkpoint['model'])

print('\n[Summary]')
print(f'best epoch:  {best_checkpoint["epoch"]}')
print(f'val score:   {best_checkpoint["metrics"]["val"]}')
print(f'test score:  {best_checkpoint["metrics"]["test"]}')

* [epoch] 0   | val: loss=0.5031 roc_auc=0.8309 f1=0.7735 | test: loss=0.5018 roc_auc=0.8320 f1=0.7757
* [epoch] 1   | val: loss=0.4925 roc_auc=0.8350 f1=0.7782 | test: loss=0.4917 roc_auc=0.8358 f1=0.7805
* [epoch] 2   | val: loss=0.4891 roc_auc=0.8361 f1=0.7758 | test: loss=0.4883 roc_auc=0.8368 f1=0.7783
* [epoch] 3   | val: loss=0.4895 roc_auc=0.8365 f1=0.7779 | test: loss=0.4887 roc_auc=0.8374 f1=0.7802
* [epoch] 4   | val: loss=0.4878 roc_auc=0.8368 f1=0.7750 | test: loss=0.4870 roc_auc=0.8377 f1=0.7771
* [epoch] 5   | val: loss=0.4871 roc_auc=0.8374 f1=0.7763 | test: loss=0.4864 roc_auc=0.8383 f1=0.7781
* [epoch] 6   | val: loss=0.4863 roc_auc=0.8383 f1=0.7755 | test: loss=0.4854 roc_auc=0.8391 f1=0.7769
* [epoch] 7   | val: loss=0.4836 roc_auc=0.8396 f1=0.7790 | test: loss=0.4828 roc_auc=0.8404 f1=0.7811
* [epoch] 8   | val: loss=0.4829 roc_auc=0.8403 f1=0.7807 | test: loss=0.4823 roc_auc=0.8410 f1=0.7828
* [epoch] 9   | val: loss=0.4824 roc_auc=0.8405 f1=0.7799 | test: loss=0.4818 roc_auc=0.8412 f1=0.7819
* [epoch] 10  | val: loss=0.4821 roc_auc=0.8408 f1=0.7798 | test: loss=0.4814 roc_auc=0.8415 f1=0.7813
* [epoch] 11  | val: loss=0.4826 roc_auc=0.8409 f1=0.7791 | test: loss=0.4819 roc_auc=0.8415 f1=0.7804
* [epoch] 12  | val: loss=0.4816 roc_auc=0.8411 f1=0.7793 | test: loss=0.4809 roc_auc=0.8417 f1=0.7806
* [epoch] 13  | val: loss=0.4812 roc_auc=0.8411 f1=0.7816 | test: loss=0.4806 roc_auc=0.8418 f1=0.7833
* [epoch] 14  | val: loss=0.4814 roc_auc=0.8411 f1=0.7820 | test: loss=0.4809 roc_auc=0.8417 f1=0.7833
* [epoch] 15  | val: loss=0.4810 roc_auc=0.8413 f1=0.7805 | test: loss=0.4806 roc_auc=0.8418 f1=0.7815
  [epoch] 16  | val: loss=0.4808 roc_auc=0.8413 f1=0.7821 | test: loss=0.4804 roc_auc=0.8418 f1=0.7831
  [epoch] 17  | val: loss=0.4812 roc_auc=0.8413 f1=0.7784 | test: loss=0.4807 roc_auc=0.8418 f1=0.7801
* [epoch] 18  | val: loss=0.4810 roc_auc=0.8414 f1=0.7787 | test: loss=0.4806 roc_auc=0.8418 f1=0.7798
  [epoch] 19  | val: loss=0.4810 roc_auc=0.8414 f1=0.7789 | test: loss=0.4807 roc_auc=0.8418 f1=0.7801
  [epoch] 20  | val: loss=0.4807 roc_auc=0.8414 f1=0.7812 | test: loss=0.4804 roc_auc=0.8417 f1=0.7820
  [epoch] 21  | val: loss=0.4810 roc_auc=0.8413 f1=0.7813 | test: loss=0.4807 roc_auc=0.8417 f1=0.7821
  [epoch] 22  | val: loss=0.4812 roc_auc=0.8412 f1=0.7787 | test: loss=0.4809 roc_auc=0.8416 f1=0.7800
  [epoch] 23  | val: loss=0.4814 roc_auc=0.8411 f1=0.7801 | test: loss=0.4811 roc_auc=0.8415 f1=0.7816
  [epoch] 24  | val: loss=0.4814 roc_auc=0.8411 f1=0.7792 | test: loss=0.4812 roc_auc=0.8414 f1=0.7804
  [epoch] 25  | val: loss=0.4816 roc_auc=0.8410 f1=0.7804 | test: loss=0.4813 roc_auc=0.8414 f1=0.7813
  [epoch] 26  | val: loss=0.4815 roc_auc=0.8409 f1=0.7776 | test: loss=0.4812 roc_auc=0.8413 f1=0.7793
  [epoch] 27  | val: loss=0.4818 roc_auc=0.8408 f1=0.7776 | test: loss=0.4816 roc_auc=0.8411 f1=0.7793
  [epoch] 28  | val: loss=0.4816 roc_auc=0.8407 f1=0.7803 | test: loss=0.4814 roc_auc=0.8410 f1=0.7818
  [epoch] 29  | val: loss=0.4817 roc_auc=0.8406 f1=0.7800 | test: loss=0.4816 roc_auc=0.8408 f1=0.7820
  [epoch] 30  | val: loss=0.4819 roc_auc=0.8404 f1=0.7799 | test: loss=0.4818 roc_auc=0.8407 f1=0.7816
  [epoch] 31  | val: loss=0.4822 roc_auc=0.8402 f1=0.7791 | test: loss=0.4820 roc_auc=0.8406 f1=0.7809
  [epoch] 32  | val: loss=0.4822 roc_auc=0.8402 f1=0.7804 | test: loss=0.4819 roc_auc=0.8405 f1=0.7819
  [epoch] 33  | val: loss=0.4821 roc_auc=0.8402 f1=0.7788 | test: loss=0.4822 roc_auc=0.8403 f1=0.7802
  [epoch] 34  | val: loss=0.4824 roc_auc=0.8401 f1=0.7788 | test: loss=0.4824 roc_auc=0.8402 f1=0.7803
  [epoch] 35  | val: loss=0.4828 roc_auc=0.8398 f1=0.7798 | test: loss=0.4829 roc_auc=0.8399 f1=0.7811

[Summary]
best epoch:  18
val score:   {'roc_auc': 0.8413896279375701, 'loss': 0.48100337386131287, 'accuracy': 0.7558433331123438, 'precision': 0.7725333827893175, 'recall': 0.7849806840667106, 'f1': 0.7787072954152451}
test score:  {'roc_auc': 0.8418316684630571, 'loss': 0.4805724024772644, 'accuracy': 0.7563099987624564, 'precision': 0.7717883865528506, 'recall': 0.7880493263891878, 'f1': 0.7798340982419525}